name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, sqlite, json

    - name: Copy .env
      run: cp .env.example .env

    - name: Set up database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Configure Environment Variables
      run: |
        echo "APP_NAME=E_vignette
        APP_ENV=local
        APP_KEY=${{ secrets.APP_KEY }}
        APP_DEBUG=true
        APP_URL=http://localhost

        LOG_CHANNEL=stack
        LOG_DEPRECATIONS_CHANNEL=null
        LOG_LEVEL=debug

        DB_CONNECTION=sqlite
        DB_DATABASE=database/database.sqlite

        BROADCAST_DRIVER=log
        CACHE_DRIVER=file
        FILESYSTEM_DISK=local
        QUEUE_CONNECTION=sync
        SESSION_DRIVER=file
        SESSION_LIFETIME=120

        MEMCACHED_HOST=127.0.0.1

        REDIS_HOST=127.0.0.1
        REDIS_PASSWORD=null
        REDIS_PORT=6379

        MAIL_MAILER=smtp
        MAIL_HOST=smtp.gmail.com
        MAIL_PORT=587
        MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
        MAIL_ENCRYPTION=tls
        MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}
        MAIL_FROM_NAME=\"E_vignette\"

        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION=us-east-1
        AWS_BUCKET=
        AWS_USE_PATH_STYLE_ENDPOINT=false

        PUSHER_APP_ID=
        PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}
        PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}
        PUSHER_HOST=
        PUSHER_PORT=443
        PUSHER_SCHEME=https
        PUSHER_APP_CLUSTER=mt1

        VITE_PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}
        VITE_PUSHER_HOST=${{ secrets.PUSHER_HOST }}
        VITE_PUSHER_PORT=${{ secrets.PUSHER_PORT }}
        VITE_PUSHER_SCHEME=${{ secrets.PUSHER_SCHEME }}
        VITE_PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}
        " > .env

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test

